import requests
import time
from pprint import pprint

BASE_URL = "http://localhost:8000"

def get_state():
    print(f"\n--- GET /env/state ---")
    res = requests.get(f"{BASE_URL}/env/state")
    if res.status_code != 200:
        print("Failed to get state:", res.text)
        return None
    data = res.json()
    print(f"User: {data['user']['name']} ({data['user']['email']})")
    print(f"Calendars: {len(data['calendars'])}")
    print(f"Events: {len(data['events'])}")
    for e in data['events']:
        print(f"  - [ID: {e['id']}] {e['title']} ({e['start_time']} to {e['end_time']})")
    return data

def reset_env():
    print(f"\n--- POST /env/reset ---")
    payload = {
        "seed_events": [
            {
                "title": "Seed Event 1",
                "start_time": "2026-04-01T10:00:00+00:00",
                "end_time": "2026-04-01T11:00:00+00:00",
                "is_all_day": False,
                "calendar_id": 1
            }
        ]
    }
    res = requests.post(f"{BASE_URL}/env/reset", json=payload)
    if res.status_code != 200:
        print("Failed to reset:", res.text)
        return
    print("Reset successful. New state:")
    data = res.json()
    for e in data['events']:
        print(f"  - [ID: {e['id']}] {e['title']} ({e['start_time']} to {e['end_time']})")

def step_env(action, payload):
    print(f"\n--- POST /env/step (Action: {action}) ---")
    req = {
        "action": action,
        "payload": payload
    }
    res = requests.post(f"{BASE_URL}/env/step", json=req)
    if res.status_code != 200:
        print(f"Step failed ({res.status_code}):", res.text)
        return None
    data = res.json()
    print(f"Success: {data['success']}")
    print(f"Message: {data['message']}")
    print(f"Events after step: {len(data['state']['events'])}")
    for e in data['state']['events']:
        print(f"  - [ID: {e['id']}] {e['title']} ({e['start_time']} to {e['end_time']})")
    return data

def main():
    print("Testing RL Environment Endpoints...")
    time.sleep(1) # Ensure server is ready if just started
    
    # 1. Get initial state
    get_state()
    
    # 2. Reset and seed an event
    reset_env()
    
    # Wait for clarity
    time.sleep(0.5)
    
    # 3. Step: Create event
    res = step_env("create_event", {
        "title": "Agent Created Event",
        "description": "This is generated by the RL test script",
        "start_time": "2026-04-02T13:00:00+00:00",
        "end_time": "2026-04-02T14:30:00+00:00",
        "is_all_day": False
    })
    
    if not res or not res['success']:
        print("Failed to complete test.")
        return
        
    created_event_id = None
    for e in res['state']['events']:
        if e['title'] == "Agent Created Event":
            created_event_id = e['id']
            break
            
    if not created_event_id:
        print("Could not find created event in state!")
        return
        
    # Wait for clarity
    time.sleep(0.5)

    # 4. Step: Move event
    step_env("move_event", {
        "id": created_event_id,
        "start_time": "2026-04-02T14:00:00+00:00",
        "end_time": "2026-04-02T15:30:00+00:00"
    })
    
    # Wait for clarity
    time.sleep(0.5)
    
    # 5. Step: Delete event
    step_env("delete_event", {
        "id": created_event_id
    })
    
    print("\n--- Testing Complete ---")
    
if __name__ == "__main__":
    main()
